Swagger 적용
Yapp-17th/Web_2_Backend pull request #14
Opened 2020-11-12 15:40 UTC by MoonYeeun

## 수정 사항
- 세션에 저장된 유저 id 사용할 수 있도록 질문리스트 컨트롤러 수정

## 추가 사항 
- swagger 적용
서버 실행 후 http://localhost:8080/swagger-ui.html 에서 확인가능

## 참고 사항
프론트 분들 작업하시려면 저희 현재 만든 부분까지 yapp 서버에 올려야 할 것 같네용..

2020-11-13 03:15 UTC, sjh2428 requested changes
수고하셨습니다!

이제 테스트케이스도 수정해주시면 좋겠습니다 :D

```java
// ...
MockHttpSession mockHttpSession = new MockHttpSession();
AccountSession accountSession = new AccountSession(userId, email, name);
mockHttpSession.setAttribute("user", accountSession);
// ...
mvc.perform(post("/self/question")
                .session(mockHttpSession)
                .contentType(MediaType.APPLICATION_JSON_VALUE)
// ...
```

`BeforeEach` 어노테이션 안에서 처리할 수 있을 것 같아요~

2020-11-13 16:41 UTC, MoonYeeun commented
## 변경 사항
- 기존 swagger에 문제가 있어서 일단 swaggerconfig 파일 수정하였습니다.
- 변경하고 보니 스프링시큐리티 때문에 swagger ui 가 보이지 않는 문제가 발생하여서   
임시로 질문/질문리스트 api url 을 수정해놓은 상태입니다..
- test코드도 재호님 말씀하신 부분이랑 api url 변경부분에 맞춰서 수정하였습니다.

## 참고 사항
- 재호님이 swagger 부분에서 더 좋은 방법이 있으시다면.. 그렇게 수정하셔도 아주 좋을 것 같습니당

2020-11-13 17:21 UTC, sjh2428 approved these changes
새벽까지 수고 많으셨습니다 ㅋㅋ

제가 코멘트 달아놓은 곳 보시구 수정하실 부분 수정 후에 머지하시면 될 것 같습니다~ :D

2020-11-13 17:21 UTC, sjh2428 commented on src/main/resources/application.yml
> +      ddl-auto: update
테스트 부분은 create-drop으로 유지하는 것이 좋겠습니다~

이전 테스트 데이터가 살아있으면 테스트가 제대로 진행이 되지 않네요 ㅠㅠ..

2020-11-13 17:21 UTC, sjh2428 commented on src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
> +    }
옹? 회원가입이 진행되지 않은(DB에 없는) `userId`, `email`, `name`으로(유저 데이터로) 세션을 설정해놓았을 때 

질문리스트 테케 서비스로직에서 `NotFoundUser` 에러를 던지는것 없이 잘 진행되나요??

2020-11-14 05:50 UTC, MoonYeeun commented on src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
> +    }
아니요 NotFoundUser 에러나서 재호님께서 작성해주신 로그인테스트 부분 실행한 후에 나머지부분 테스트 진행했어요..! ㅠㅠ
이렇ㄱㅔ 안하고 다른 방법이 있나요,, ?

2020-11-14 16:02 UTC, sjh2428 commented on src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
> +    }
저도 그게 약간 걸리긴 해요 ㅠ
1. `@BeforeEach`에서 매번 세션이 없다면 새로 넣어주는 체크로직을 수행해야 하는가
2. `findById`를 해서 가입되어있는 아이디인지 체크하고 가입되어있지 않다면 `Repository`로 `save`해줘야하는지 ㅠ..

그런데 테스트케이스는 서로 종속되면 안되기 때문에.. 이것들을 다 해야할 것 같은 생각이 듭니다..! T^T
아닐 수도 있지만요 ㅠㅠ 어렵네요 ㅜ

2020-11-15 13:23 UTC, MoonYeeun commented
## 변경 사항
- 재호님 말씀대로 ` @BeforeEach에서 회원가입 & 세션 넣어주는 로직` 처리하도록 수정했습니다!
- 그리고 질문리스트도 미리 생성해야 질문리스트 수정 test, 질문 관련 test에서 사용할 수 있을 것 같아서 질문리스트 생성 로직도 @BeforeEach로

2020-11-15 13:33 UTC, MoonYeeun commented on src/main/java/com/witherview/database/entity/QuestionList.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "belongList", cascade = CascadeType.ALL, orphanRemoval = true)
## 이슈 사항
테스트 코드에서 질문리스트도 미리 생성해놔야 질문리스트 수정 test, 질문 관련 test에서 사용할 수 있을 것 같아서 질문리스트 생성 로직도 @BeforeEach로 추가했는데 
이 때, `LazyInitializationException: failed to lazily initialize a collection of role:` 발생하더라구요..   

그래서 User, QuestionList 엔티티에서 즉시로딩으로 바꿔서 처리하도록 일단 수정해놨는데 실제 서버 동작할 때는 성능상 이렇게 하면 안될 것 같다는 생각이 듭니당 😭
이걸 어떻게 처리하면 좋을까요.. test 코드 실행할 때만 바꾸는 걸로 해야할까욬ㅋㅋㅋㅋㅋ 아니면 더 좋은 방법이 있을라나요....

2020-11-15 20:27 UTC, sjh2428 reviewed
수고하셨습니다 :)

저도 한번 검색해보고 했는데 자세히는 나와있는게 없네요 ㅠ

약간의 도움을 받은 곳은 이곳정도..?
https://www.inflearn.com/questions/33949

이유는 자세히 알아봐야 할 것 같아요~

2020-11-15 20:27 UTC, sjh2428 commented on src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
> +        questionListRepository.save(questionList);
`questionList`가 없을 경우에 `save`하는 방식으로 해주세요!

안그러면 테스트케이스 갯수만큼 DB에 질문리스트가 추가될 것 같네요~ :D

2020-11-15 20:27 UTC, sjh2428 commented on src/test/java/com/witherview/selfPractice/SelfPracticeSupporter.java
> +        mockHttpSession.setAttribute("user", accountSession);
이 부분도 mock session이 없다면 set하는 것은 어떤가요? :D

2020-11-15 20:27 UTC, sjh2428 commented on src/test/java/com/witherview/selfPractice/SelfQuestionApiTest.java
> +    }
다음과 같이 하나의 메소드 안에다가 작성하시고 테스트 클래스에다가 Transactional을 붙이시면 해결 되실 것 같아요~

안되던 이유는 음.. 더 찾아봐야 할 것 같은데 추정하기로는
1. BeforeEach가 어떤 것 부터 시작되는지가 보장이 안됨 (틀릴 수 있습니다)
2. 하나의 트랜잭션 안에서 테스트 전 로직이 전부 실행되지 않아 영속성 문제가 발생(유력)

`listId`, `questionId`가 고정되어 있어서 테스트가 실패하는게 있네요~ :D

```suggestion
@Transactional
public class SelfQuestionApiTest extends SelfPracticeSupporter {

    @Autowired
    QuestionRepository questionRepository;

    @BeforeEach
    public void 미리질문등록() {
        User user = userRepository.findByEmail(email);
        if (user == null) {
            user = userRepository.save(new User(email, passwordEncoder.encode(password), name));
        }
        AccountSession accountSession = new AccountSession(userId, email, name);
        mockHttpSession.setAttribute("user", accountSession);

        QuestionList questionList = new QuestionList("title", "enterprise", "job");
        user.addQuestionList(questionList);
        questionListRepository.save(questionList);

        Question question = new Question("question", "answer", 1);
        questionList.addQuestion(question);
        questionRepository.save(question);
    }
```

2020-11-15 20:34 UTC, sjh2428 requested changes
Request Change 드리겠습니다 ㅎㅎ

2020-11-16 13:58 UTC, MoonYeeun commented
## 수정 사항
일단 재호님 말씀대로 수정하였습니다~!

근데 진짜 테스트 클래스에다가 @Transactional을 넣어두니 자동 Rollback이 되어 
테스트코드 실행할 때마다 questionLIst, session 계속 새로 생성해주는 것 같네요.. ㅠㅠ (값 없을 때만 넣는게 의미없는...ㅠ)

그리고 

> 상위 클래스에서는 메소드가 하나이니 회원가입_세션생성_리스트생성()메소드에 트랜잭션을 붙여도 정상 동작합니다~

>저도 여기서 의문점.. ㅋㅋㅋ
>@BeforeEach안에서만 트랜잭션을 유지시켜줘도 되지 않나요..? 굳이 mockMvc를 이용한 테스트 메소드까지 트랜잭션을 입혀주어야 하는건가.. ㅠㅠ

재호님 말씀처럼 상위클래스의 메소드가 하나여서  회원가입_세션생성_리스트생성()메소드에 트랜잭션 붙여봤더니 여전히
` LazyInitializationException` 뜨더라구요... 
클래스에 @Transactional 붙여줘야 잘 작동하는 것을 보니 뭔가 차이가 있긴 한 것 같습니다.. (찾아봐도 명확한 해답이 안나오네용  ㅠ)

그리고 애초에 test 코드에 @Transactional 을 붙이지 말라는 글들도 꽤 보여서 (ex) https://dev.to/henrykeys/don-t-use-transactional-in-tests-40eb) 이게 맞는건가 라는 의문점도 들긴합니다...

https://anomie7.tistory.com/68 이분은 저희랑 비슷한 상황이셨는데 
@BeforeEach로 엔티티를 저장하지 않고 직접 sql로 데이터를 저장하셨다네요 ㅎㅎ

2020-11-17 05:46 UTC, sjh2428 approved these changes
> 재호님 말씀처럼 상위클래스의 메소드가 하나여서 회원가입_세션생성_리스트생성()메소드에 트랜잭션 붙여봤더니 여전히
> LazyInitializationException 뜨더라구요...

아 그런가요? 제 컴퓨터에서는 상위 클래스 메소드에다가만 트랜잭션 붙이고 하위 클래스에서는 클래스에다가 트랜잭션 붙였더니 되더군요..! T^T 

> 클래스에 @transactional 붙여줘야 잘 작동하는 것을 보니 뭔가 차이가 있긴 한 것 같습니다.. (찾아봐도 명확한 해답이 안나오네용 ㅠ)

이건 한번 찾아보겠습니다 :)

> 근데 진짜 테스트 클래스에다가 @transactional을 넣어두니 자동 Rollback이 되어
> 테스트코드 실행할 때마다 questionLIst, session 계속 새로 생성해주는 것 같네요.. ㅠㅠ (값 없을 때만 넣는게 의미없는...ㅠ)

예은님 말씀이 맞는 것 같아요~ 체크하는 로직은 없어도 될 것 같아요 :D

sql로 직접 한 것은.. 저는 선호하지는 않을 것 같습니다 ㅎㅎ ㅋㅋㅋ

수고하셨습니다! :D

2020-11-17 13:16 UTC, merged